# CLUES MESOS configuration
- ini_file: dest=/etc/clues2/clues2.cfg section=general option=LRMS_CLASS value=cluesplugins.mesos
  notify: restart cluesd
- copy: src=/etc/clues2/conf.d/plugin-mesos.cfg-example dest=/etc/clues2/conf.d/plugin-mesos.cfg force=no
  notify: restart cluesd
- ini_file: dest=/etc/clues2/conf.d/plugin-mesos.cfg section=MESOS option=MESOS_SERVER value=mesosserverpublic
  notify: restart cluesd

- file: path=/etc/clues2/ state=directory
- copy:
   content: |
     {% for number in range(1, ec3_max_instances|int + 1) %}
     {{vnode_prefix}}{{number}}
     {% endfor %}
   dest: "/etc/clues2/mesos_vnodes.info"
